### ISSUE TITLE
华为p40 

### ISSUE THREAD

**Issue by DWNEWS-jixiaohong** [zebateira/react-use-system-theme#14]
看了一下大概的逻辑 ，应该也是使用的
`window.matchMedia("(prefers-color-scheme: dark)")`
这个去做的判断，不过我在华为p40 还有1+手机 获取到手机系统的MediaQueryList是{} 
有检测一下这两个手机嘛？

**Comment by zebateira** [comment]
Haven't tested on those two specific devices no.
Welcome to a PR that fixes the issue though! 🙏
