### ISSUE TITLE
Could not resolve dependency: peer react@"^16.12.0"

### ISSUE THREAD

**Issue by deadcoder0904** [zebateira/react-use-system-theme#8]
When I try to do `npm i react-use-system-theme`, I get the following error:

> npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.12.0" from react-use-system-theme@1.1.1
npm ERR! node_modules/react-use-system-theme
npm ERR!   react-use-system-theme@"*" from the root project
npm ERR!

Can you publish a new version with a bumped up peer dependency? Or just a wildcard `react@*` would be perfect for all future versions :)

**Comment by deadcoder0904** [comment]
I couldn't install it so I copy-pasted it locally while converting it to TypeScript like:

```tsx
import React from 'react'

const useIsomorphicLayoutEffect =
	typeof window !== 'undefined' ? React.useLayoutEffect : React.useEffect

export const colorSchemes = {
	light: '(prefers-color-scheme: light)',
	dark: '(prefers-color-scheme: dark)',
}

function onThemeChange(callback: Function) {
	return (event: any) => {
		if (!event || !event.matches) return
		callback()
	}
}

export const useSystemTheme = (initialTheme: 'dark' | 'light') => {
	const [theme, setTheme] = React.useState(initialTheme || null)

	React.useEffect(() => {
		// SSR or matchMedia not supported
		if (typeof window === 'undefined' || !window.matchMedia) {
			return
		}

		const lightMatch = window.matchMedia(colorSchemes.light)
		const onLightMatches = onThemeChange(() => setTheme('light'))

		lightMatch.addListener(onLightMatches)

		const darkMatch = window.matchMedia(colorSchemes.dark)
		const onDarkMatches = onThemeChange(() => setTheme('dark'))

		darkMatch.addListener(onDarkMatches)

		return () => {
			lightMatch.removeListener(onLightMatches)
			darkMatch.removeListener(onDarkMatches)
		}
	}, [])

	useIsomorphicLayoutEffect(() => {
		// SSR or matchMedia not supported
		if (typeof window === 'undefined' || !window.matchMedia) {
			return
		}

		if (window.matchMedia(colorSchemes.dark).matches && theme !== 'dark') {
			setTheme('dark')
		} else if (window.matchMedia(colorSchemes.light).matches && theme !== 'light') {
			setTheme('light')
		}
	}, [theme])

	return theme
}
```

Which worked perfectly.

However, when I log into the console like:

```js
console.log(useSystemTheme('light'))
```

It gave 2 logs thanks to React re-rendering. I put it in a `button`'s `onClick` & it gave perfect system theme only once so that is not my problem.

But why does it take an input? After all, it simply has to get the system theme. It can be like `useSystemTheme()`? Am I missing anything?

**Comment by zebateira** [comment]
Thank you for reporting this 👍 Will look into it soon.

> However, when I log into the console like:
> 
> ```js
> console.log(useSystemTheme('light'))
> ```
> 
> It gave 2 logs thanks to React re-rendering. I put it in a `button`'s `onClick` & it gave perfect system theme only once so that is not my problem.
> 
> But why does it take an input? After all, it simply has to get the system theme. It can be like `useSystemTheme()`? Am I missing anything?

The parameter you pass onto it is the [initial theme](https://github.com/zebateira/react-use-system-theme#usage) you want to use to render the UI until the system theme is provided. Meaning, until your app knows what the user's system theme is, you need to choose one theme to render. It's equivalent to `useSystemTheme() || 'light'`, but I added it as a parameter just as a helper. Let me know if this makes sense.

**Comment by deadcoder0904** [comment]
Oh, I switched to using https://github.com/xcv58/use-system-theme as it feels simpler :)
